// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/auth/error" | "/[locale]/auth/sign-in" | "/[locale]/auth/sign-up-success" | "/[locale]/auth/update-password" | "/[locale]/dashboard" | "/[locale]/dashboard/categories" | "/[locale]/dashboard/categories/[id]" | "/[locale]/dashboard/categories/new" | "/[locale]/dashboard/products" | "/[locale]/dashboard/products/[id]" | "/[locale]/dashboard/products/new" | "/[locale]/onboarding" | "/[locale]/products/[slug]"
type AppRouteHandlerRoutes = "/[locale]/auth/confirm"
type PageRoutes = never
type LayoutRoutes = "/[locale]" | "/[locale]/dashboard" | "/[locale]/dashboard/products"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/[locale]": { "locale": string; }
  "/[locale]/auth/confirm": { "locale": string; }
  "/[locale]/auth/error": { "locale": string; }
  "/[locale]/auth/sign-in": { "locale": string; }
  "/[locale]/auth/sign-up-success": { "locale": string; }
  "/[locale]/auth/update-password": { "locale": string; }
  "/[locale]/dashboard": { "locale": string; }
  "/[locale]/dashboard/categories": { "locale": string; }
  "/[locale]/dashboard/categories/[id]": { "locale": string; "id": string; }
  "/[locale]/dashboard/categories/new": { "locale": string; }
  "/[locale]/dashboard/products": { "locale": string; }
  "/[locale]/dashboard/products/[id]": { "locale": string; "id": string; }
  "/[locale]/dashboard/products/new": { "locale": string; }
  "/[locale]/onboarding": { "locale": string; }
  "/[locale]/products/[slug]": { "locale": string; "slug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/[locale]": never
  "/[locale]/dashboard": never
  "/[locale]/dashboard/products": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
