// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/[locale]/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../app/[locale]/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[locale]/(public)/products/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/products/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/[locale]/(public)/products/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[locale]/auth/error/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auth/error">> = Specific
  const handler = {} as typeof import("../../../app/[locale]/auth/error/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[locale]/auth/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auth/sign-in">> = Specific
  const handler = {} as typeof import("../../../app/[locale]/auth/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[locale]/auth/sign-up-success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auth/sign-up-success">> = Specific
  const handler = {} as typeof import("../../../app/[locale]/auth/sign-up-success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[locale]/auth/update-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auth/update-password">> = Specific
  const handler = {} as typeof import("../../../app/[locale]/auth/update-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[locale]/dashboard/categories/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/categories/[id]">> = Specific
  const handler = {} as typeof import("../../../app/[locale]/dashboard/categories/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[locale]/dashboard/categories/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/categories/new">> = Specific
  const handler = {} as typeof import("../../../app/[locale]/dashboard/categories/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[locale]/dashboard/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/categories">> = Specific
  const handler = {} as typeof import("../../../app/[locale]/dashboard/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[locale]/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/[locale]/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[locale]/dashboard/products/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/products/[id]">> = Specific
  const handler = {} as typeof import("../../../app/[locale]/dashboard/products/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[locale]/dashboard/products/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/products/new">> = Specific
  const handler = {} as typeof import("../../../app/[locale]/dashboard/products/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[locale]/dashboard/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/products">> = Specific
  const handler = {} as typeof import("../../../app/[locale]/dashboard/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[locale]/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/onboarding">> = Specific
  const handler = {} as typeof import("../../../app/[locale]/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[locale]/auth/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/auth/confirm">> = Specific
  const handler = {} as typeof import("../../../app/[locale]/auth/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/[locale]/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../app/[locale]/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[locale]/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/[locale]/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[locale]/dashboard/products/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/dashboard/products">> = Specific
  const handler = {} as typeof import("../../../app/[locale]/dashboard/products/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../../app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
